### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by tomkimsour** [ZettaScaleLabs/ros-z#1]
I was not able to run any of the examples. The nodes would be hanging for a while.

For instance, I have run :
`cargo run --example z_server`

Then in my debugger run `cargo run --example z_client` and noticed it would hand on the receiving function. https://github.com/ZettaScaleLabs/ros-z/blob/main/ros-z/src/service.rs#L86

Any lead on how to resolve this issue ? I would be happy to help but I am unsure where to look at.

**Comment by YuanYuYuan** [comment]
Hi @tomkimsour! I just pushed a significant set of updates to the project (it took us a while to optimize the design 😅). I’ve confirmed that the following examples work on my side. Could you pull the latest changes and give them a try?

```bash
cargo run --example z_server
cargo run --example z_client
```

**Comment by tomkimsour** [comment]
Hi, I still have the same behavior. Nothing prints out when running them. z_client hangs there https://github.com/ZettaScaleLabs/ros-z/blob/main/ros-z/src/service.rs#L90

**Comment by tomkimsour** [comment]
Ah yes right. I remember setting this in the past. I did not have multicast on localhost. Thanks for the guidance
